import { Parent } from "./parent";

export const PARENTS: Parent[] = [
    {
      id: 1,
      nom: "Dupont",
      prenom: "Pierre",
      adresseEmail: "pierre.dupont@example.com",
      adresse: "123 Rue de Paris, Paris, France",
      nationalite: "Camerounais",
      sexe: "Masculin",
      picture: "assets/homme.png",
      profession: "Ingénieur",
      telephone: "+33 1 23 45 67 89",
      listeDesEnfants: [
        {
          id: 1,
          matricule: "ELE12345",
          nom: "Dupont",
          prenom: "Marie",
          email: "marie.dupont@example.com",
          dateNaissance: new Date(2007, 5, 15),
          lieuNaissance: "Paris",
          niveau: "Terminale",
          specialite: "Mathématiques",
          adresse: "123 Rue de Paris, Paris, France",
          sexe: "F",
          classe: "T3",
          picture: "https://example.com/marie.png",
          section: "Scientifique",
          typeEnseignement: "Général",
          natureEnseignement: "Public",
          cycle: "Lycée",
          telephone: "+33 1 98 76 54 32",
          ville: "Paris",
          nationalite: "Française",
          nomDuPere: "Pierre Dupont",
          nomDeLaMere: "Sophie Dupont",
          enseignants: [],
          matieres: [],
          notes: [],
          scolarites: []
        },
        {
          id: 2,
          matricule: "ELE67890",
          nom: "Dupont",
          prenom: "Lucas",
          email: "lucas.dupont@example.com",
          dateNaissance: new Date(2010, 3, 22),
          lieuNaissance: "Paris",
          niveau: "4ème",
          specialite: "Informatique",
          adresse: "123 Rue de Paris, Paris, France",
          sexe: "M",
          classe: "4A",
          picture: "https://example.com/lucas.png",
          section: "Technologique",
          typeEnseignement: "Général",
          natureEnseignement: "Public",
          cycle: "Collège",
          telephone: "+33 1 45 67 89 23",
          ville: "Paris",
          nationalite: "Française",
          nomDuPere: "Pierre Dupont",
          nomDeLaMere: "Sophie Dupont",
          enseignants: [],
          matieres: [],
          notes: [],
          scolarites: []
        }
      ]
    },
    {
      id: 2,
      nom: "Martin",
      prenom: "Claire",
      adresseEmail: "claire.martin@example.com",
      adresse: "45 Avenue de Lyon, Lyon, France",
      nationalite: "Camerounaise",
      sexe: "Féminin",
      picture: "assets/femme.png",
      profession: "Médecin",
      telephone: "+33 4 56 78 90 12",
      listeDesEnfants: [
        {
          id: 3,
          matricule: "ELE11223",
          nom: "Martin",
          prenom: "Alice",
          email: "alice.martin@example.com",
          dateNaissance: new Date(2005, 9, 10),
          lieuNaissance: "Lyon",
          niveau: "Première",
          specialite: "Physique-Chimie",
          adresse: "45 Avenue de Lyon, Lyon, France",
          sexe: "F",
          classe: "P2",
          picture: "https://example.com/alice.png",
          section: "Scientifique",
          typeEnseignement: "Général",
          natureEnseignement: "Privé",
          cycle: "Lycée",
          telephone: "+33 4 78 56 12 34",
          ville: "Lyon",
          nationalite: "Française",
          nomDuPere: "Jean Martin",
          nomDeLaMere: "Claire Martin",
          enseignants: [],
          matieres: [],
          notes: [],
          scolarites: []
        }
      ]
    },
    {
      id: 3,
      nom: "Nguyen",
      prenom: "Thi",
      adresseEmail: "thi.nguyen@example.com",
      adresse: "67 Rue de Hanoi, Marseille, France",
      nationalite: "Camerounais",
      sexe: "Masculin",
      picture: "assets/homme.png",
      profession: "Professeur",
      telephone: "+33 4 98 76 54 32",
      listeDesEnfants: [
        {
          id: 4,
          matricule: "ELE22334",
          nom: "Nguyen",
          prenom: "Bao",
          email: "bao.nguyen@example.com",
          dateNaissance: new Date(2011, 7, 25),
          lieuNaissance: "Marseille",
          niveau: "6ème",
          specialite: "Informatique",
          adresse: "67 Rue de Hanoi, Marseille, France",
          sexe: "M",
          classe: "6B",
          picture: "https://example.com/bao.png",
          section: "Général",
          typeEnseignement: "Général",
          natureEnseignement: "Public",
          cycle: "Collège",
          telephone: "+33 4 67 89 45 23",
          ville: "Marseille",
          nationalite: "Française",
          nomDuPere: "Minh Nguyen",
          nomDeLaMere: "Thi Nguyen",
          enseignants: [],
          matieres: [],
          notes: [],
          scolarites: []
        }
      ]
    },

    {
        id: 4,
        nom: "Lemoine",
        prenom: "Sophie",
        adresseEmail: "sophie.lemoine@example.com",
        adresse: "15 Boulevard des Fleurs, Nice, France",
        nationalite: "Camerounaise",
        sexe: "Féminin",
        picture: "assets/femme.png",
        profession: "Avocate",
        telephone: "+33 4 93 45 67 89",
        listeDesEnfants: [
          {
            id: 5,
            matricule: "ELE33456",
            nom: "Lemoine",
            prenom: "Lucas",
            email: "lucas.lemoine@example.com",
            dateNaissance: new Date(2009, 1, 20),
            lieuNaissance: "Nice",
            niveau: "5ème",
            specialite: "Sciences",
            adresse: "15 Boulevard des Fleurs, Nice, France",
            sexe: "M",
            classe: "5C",
            picture: "https://example.com/lucas.png",
            section: "Général",
            typeEnseignement: "Privé",
            natureEnseignement: "Catholique",
            cycle: "Collège",
            telephone: "+33 4 56 78 12 34",
            ville: "Nice",
            nationalite: "Française",
            nomDuPere: "Jean Lemoine",
            nomDeLaMere: "Sophie Lemoine",
            enseignants: [],
            matieres: [],
            notes: [],
            scolarites: []
          }
        ]
      },
      {
        id: 5,
        nom: "Diallo",
        prenom: "Amadou",
        adresseEmail: "amadou.diallo@example.com",
        adresse: "22 Rue des Palmiers, Dakar, Sénégal",
        nationalite: "Camerounais",
        sexe: "Masculin",
        picture: "assets/homme.png",
        profession: "Entrepreneur",
        telephone: "+221 33 123 45 67",
        listeDesEnfants: [
          {
            id: 6,
            matricule: "ELE44567",
            nom: "Diallo",
            prenom: "Fatou",
            email: "fatou.diallo@example.com",
            dateNaissance: new Date(2010, 5, 10),
            lieuNaissance: "Dakar",
            niveau: "3ème",
            specialite: "Histoire",
            adresse: "22 Rue des Palmiers, Dakar, Sénégal",
            sexe: "F",
            classe: "3B",
            picture: "https://example.com/fatou.png",
            section: "Littéraire",
            typeEnseignement: "Public",
            natureEnseignement: "Laïc",
            cycle: "Collège",
            telephone: "+221 77 654 32 10",
            ville: "Dakar",
            nationalite: "Sénégalaise",
            nomDuPere: "Amadou Diallo",
            nomDeLaMere: "Mariama Diallo",
            enseignants: [],
            matieres: [],
            notes: [],
            scolarites: []
          }
        ]
      },
      {
        id: 6,
        nom: "Garcia",
        prenom: "Carlos",
        adresseEmail: "carlos.garcia@example.com",
        adresse: "78 Avenida de Madrid, Madrid, Espagne",
        nationalite: "Camerounais",
        sexe: "Masculin",
        picture: "assets/homme.png",
        profession: "Architecte",
        telephone: "+34 91 345 67 89",
        listeDesEnfants: [
          {
            id: 7,
            matricule: "ELE55678",
            nom: "Garcia",
            prenom: "Ana",
            email: "ana.garcia@example.com",
            dateNaissance: new Date(2008, 2, 15),
            lieuNaissance: "Madrid",
            niveau: "2nde",
            specialite: "Arts",
            adresse: "78 Avenida de Madrid, Madrid, Espagne",
            sexe: "F",
            classe: "2A",
            picture: "https://example.com/ana.png",
            section: "Général",
            typeEnseignement: "Public",
            natureEnseignement: "Laïc",
            cycle: "Lycée",
            telephone: "+34 91 234 56 78",
            ville: "Madrid",
            nationalite: "Espagnole",
            nomDuPere: "Carlos Garcia",
            nomDeLaMere: "Maria Garcia",
            enseignants: [],
            matieres: [],
            notes: [],
            scolarites: []
          }
        ]
      },
      {
        id: 7,
        nom: "Smith",
        prenom: "John",
        adresseEmail: "john.smith@example.com",
        adresse: "101 Central Park West, New York, USA",
        nationalite: "Camerounais",
        sexe: "Masculin",
        picture: "assets/homme.png",
        profession: "Banquier",
        telephone: "+1 212 456 7890",
        listeDesEnfants: [
          {
            id: 8,
            matricule: "ELE66789",
            nom: "Smith",
            prenom: "Emily",
            email: "emily.smith@example.com",
            dateNaissance: new Date(2006, 4, 25),
            lieuNaissance: "New York",
            niveau: "1ère",
            specialite: "Biologie",
            adresse: "101 Central Park West, New York, USA",
            sexe: "F",
            classe: "1B",
            picture: "https://example.com/emily.png",
            section: "Scientifique",
            typeEnseignement: "Public",
            natureEnseignement: "Laïc",
            cycle: "Lycée",
            telephone: "+1 917 654 3210",
            ville: "New York",
            nationalite: "Américaine",
            nomDuPere: "John Smith",
            nomDeLaMere: "Jane Smith",
            enseignants: [],
            matieres: [],
            notes: [],
            scolarites: []
          }
        ]
      },
      {
        id: 8,
        nom: "Wang",
        prenom: "Li",
        adresseEmail: "li.wang@example.com",
        adresse: "56 Route de Pékin, Pékin, Chine",
        nationalite: "Camerounais",
        sexe: "Masculin",
        picture: "assets/homme.png",
        profession: "Chercheur",
        telephone: "+86 10 1234 5678",
        listeDesEnfants: [
          {
            id: 9,
            matricule: "ELE77890",
            nom: "Wang",
            prenom: "Mei",
            email: "mei.wang@example.com",
            dateNaissance: new Date(2011, 6, 30),
            lieuNaissance: "Pékin",
            niveau: "CE2",
            specialite: "Chimie",
            adresse: "56 Route de Pékin, Pékin, Chine",
            sexe: "F",
            classe: "C3",
            picture: "https://example.com/mei.png",
            section: "Scientifique",
            typeEnseignement: "Privé",
            natureEnseignement: "Confucianiste",
            cycle: "Élémentaire",
            telephone: "+86 10 9876 5432",
            ville: "Pékin",
            nationalite: "Chinoise",
            nomDuPere: "Li Wang",
            nomDeLaMere: "Zhen Wang",
            enseignants: [],
            matieres: [],
            notes: [],
            scolarites: []
          }
        ]
      },
      {
        id: 9,
        nom: "Ivanov",
        prenom: "Sergey",
        adresseEmail: "sergey.ivanov@example.com",
        adresse: "45 Prospekt Mira, Moscou, Russie",
        nationalite: "Camerounais",
        sexe: "Masculin",
        picture: "assets/homme.png",
        profession: "Diplomate",
        telephone: "+7 495 123 45 67",
        listeDesEnfants: [
          {
            id: 10,
            matricule: "ELE88901",
            nom: "Ivanov",
            prenom: "Olga",
            email: "olga.ivanov@example.com",
            dateNaissance: new Date(2009, 11, 12),
            lieuNaissance: "Moscou",
            niveau: "5ème",
            specialite: "Géographie",
            adresse: "45 Prospekt Mira, Moscou, Russie",
            sexe: "F",
            classe: "5B",
            picture: "https://example.com/olga.png",
            section: "Scientifique",
            typeEnseignement: "Public",
            natureEnseignement: "Laïc",
            cycle: "Collège",
            telephone: "+7 495 234 56 78",
            ville: "Moscou",
            nationalite: "Russe",
            nomDuPere: "Sergey Ivanov",
            nomDeLaMere: "Nina Ivanova",
            enseignants: [],
            matieres: [],
            notes: [],
            scolarites: []
          }
        ]
      },
    
  ];
  
  
  