import { Note } from "./note";

const NOTES: Note[] = [
    // Les notes précédentes restent inchangées
    {
        id: 1,
        nomEleve: "Dubois",
        prenomEleve: "Louis",
        matiere: "Mathématiques",
        valeur: 14,
        classe: "Classe 1",
        sequence: "Sequence 1",
        enseignant: "Martin",
        observation: "Très bon travail",
        noteGenerale: 15,
        premiereNote: 13,
        derniereNote: 16,
        date: new Date(2024, 3, 12)
    },
    {
        id: 2,
        nomEleve: "Lefevre",
        prenomEleve: "Camille",
        matiere: "Français",
        valeur: 16,
        classe: "Classe 2",
        sequence: "Sequence 2",
        enseignant: "Morel",
        observation: "Excellent progrès",
        noteGenerale: 17,
        premiereNote: 15,
        derniereNote: 18,
        date: new Date(2024, 2, 25)
    },
    {
        id: 3,
        nomEleve: "Moreau",
        prenomEleve: "Lucie",
        matiere: "Physique-Chimie",
        valeur: 18,
        classe: "Classe 3",
        sequence: "Sequence 3",
        enseignant: "Dupuis",
        observation: "Participation exceptionnelle en classe",
        noteGenerale: 19,
        premiereNote: 17,
        derniereNote: 20,
        date: new Date(2024, 4, 5)
    },
    {
        id: 4,
        nomEleve: "Leroy",
        prenomEleve: "Marie",
        matiere: "Anglais",
        valeur: 15,
        classe: "Classe 5",
        sequence: "Sequence 5",
        enseignant: "Leroy",
        observation: "Très bon travail sur cette séquence",
        noteGenerale: 16,
        premiereNote: 14,
        derniereNote: 17,
        date: new Date(2024, 1, 18)
    },
    {
        id: 5,
        nomEleve: "Jean",
        prenomEleve: "Dupond",
        matiere: "Anglais",
        valeur: 15,
        classe: "Classe 4",
        sequence: "Sequence 2",
        enseignant: "Leroy",
        observation: "Très bon travail sur cette séquence",
        noteGenerale: 16,
        premiereNote: 14,
        derniereNote: 17,
        date: new Date(2024, 1, 18)
    },
    {
        id: 6,
        nomEleve: "Maroie",
        prenomEleve: "Alain",
        matiere: "Anglais",
        valeur: 15,
        classe: "Classe 5",
        sequence: "Sequence 5",
        enseignant: "Leroy",
        observation: "Très bon travail sur cette séquence",
        noteGenerale: 16,
        premiereNote: 14,
        derniereNote: 17,
        date: new Date(2024, 1, 18)
    },
    {
        id: 7,
        nomEleve: "Leroye",
        prenomEleve: "Mariee",
        matiere: "Anglais",
        valeur: 15,
        classe: "Classe 5",
        sequence: "Sequence 6",
        enseignant: "Leroy",
        observation: "Très bon travail sur cette séquence",
        noteGenerale: 16,
        premiereNote: 14,
        derniereNote: 17,
        date: new Date(2024, 1, 18)
    },
    {
        id: 8,
        nomEleve: "Morel",
        prenomEleve: "Thomas",
        matiere: "Mathématiques",
        valeur: 16,
        classe: "Classe 4",
        sequence: "Sequence 2",
        enseignant: "Martin",
        observation: "Très bon travail",
        noteGenerale: 17,
        premiereNote: 15,
        derniereNote: 18,
        date: new Date(2024, 3, 20)
    },
    {
        id: 9,
        nomEleve: "Petit",
        prenomEleve: "Julie",
        matiere: "Français",
        valeur: 17,
        classe: "Classe 5",
        sequence: "Sequence 3",
        enseignant: "Morel",
        observation: "Excellente participation en classe",
        noteGenerale: 18,
        premiereNote: 16,
        derniereNote: 19,
        date: new Date(2024, 2, 28)
    },
    {
        id: 10,
        nomEleve: "Marie",
        prenomEleve: "Leroy",
        matiere: "Anglais",
        valeur: 15,
        classe: "Classe 8",
        sequence: "Sequence 5",
        enseignant: "Leroy",
        observation: "Très bon travail sur cette séquence",
        noteGenerale: 16,
        premiereNote: 14,
        derniereNote: 17,
        date: new Date(2024, 1, 18)
    },
    {
        id: 11,
        nomEleve: "Tientcheu",
        prenomEleve: "Evans",
        matiere: "Anglais",
        valeur: 15,
        classe: "Classe 9",
        sequence: "Sequence 5",
        enseignant: "Leroy",
        observation: "Très bon travail sur cette séquence",
        noteGenerale: 16,
        premiereNote: 14,
        derniereNote: 17,
        date: new Date(2024, 1, 18)
    },
    {
        id: 12,
        nomEleve: "Nami",
        prenomEleve: "Marie",
        matiere: "Anglais",
        valeur: 15,
        classe: "Classe 10",
        sequence: "Sequence 10",
        enseignant: "Leroy",
        observation: "Très bon travail sur cette séquence",
        noteGenerale: 16,
        premiereNote: 14,
        derniereNote: 17,
        date: new Date(2024, 1, 18)
    },
    {
        id: 13,
        nomEleve: "Girard",
        prenomEleve: "Paul",
        matiere: "Sciences",
        valeur: 15,
        classe: "Classe 1",
        sequence: "Sequence 2",
        enseignant: "Fischer",
        observation: "Bon travail, peut mieux faire",
        noteGenerale: 16,
        premiereNote: 14,
        derniereNote: 17,
        date: new Date(2024, 3, 25)
    },
    {
        id: 14,
        nomEleve: "Robin",
        prenomEleve: "Julie",
        matiere: "Français",
        valeur: 18,
        classe: "Classe 2",
        sequence: "Sequence 3",
        enseignant: "Lefevre",
        observation: "Travail exceptionnel",
        noteGenerale: 19,
        premiereNote: 17,
        derniereNote: 20,
        date: new Date(2024, 2, 10)
    },
];
