import { Enseignant } from "./enseignant";

export const ENSEIGNANTS: Enseignant[] = [
    // Les enseignants précédents restent inchangés
    {
        id: 1,
        nom: "Dupuis",
        prenom: "Émilie",
        adresseEmail: "dupuis@gmail.com",
        departement: "Département 2",
        profession: "Enseignant",
        sexe: "Féminin",
        picture: "assets/femme.png",
        nationalite: "Française",
        dateNaissance: new Date(1982, 3, 25),
        lieuNaissance: "Lyon",
        telephone: "0123456785",
        adresse: "5 Rue de la Paix",
        ville: "Paris",
        matiere1: "Physique-Chimie",
        matiere2: "SVT",
        matiere3: "Langues Vivantes",
        matiere4: "Arts Plastiques",
        matiere5: "Éducation Musicale",
        emploiDeTemps: []
    },
    {
        id: 2,
        nom: "Landry",
        prenom: "Antoine",
        adresseEmail: "landry@gmail.com",
        departement: "Département 3",
        profession: "Professeur",
        sexe: "Masculin",
        picture: "assets/homme.png",
        nationalite: "Française",
        dateNaissance: new Date(1979, 9, 12),
        lieuNaissance: "Paris",
        telephone: "0123456786",
        adresse: "6 Rue du Commerce",
        ville: "Paris",
        matiere1: "Mathématiques",
        matiere2: "Informatique",
        matiere3: "Sciences",
        matiere4: "Géographie",
        matiere5: "Histoire",
        emploiDeTemps: []
    },
    {
        id: 3,
        nom: "Morel",
        prenom: "Sophie",
        adresseEmail: "morel@gmail.com",
        departement: "Département 1",
        profession: "Enseignante",
        sexe: "Féminin",
        picture: "assets/femme.png",
        nationalite: "Française",
        dateNaissance: new Date(1985, 6, 30),
        lieuNaissance: "Marseille",
        telephone: "0123456787",
        adresse: "7 Rue des Lilas",
        ville: "London",
        matiere1: "Français",
        matiere2: "Littérature",
        matiere3: "Philosophie",
        matiere4: "Latin",
        matiere5: "Grec",
        emploiDeTemps: []
    },
    {
        id: 4,
        nom: "Roux",
        prenom: "Julien",
        adresseEmail: "roux@gmail.com",
        departement: "Département 2",
        profession: "Professeur",
        sexe: "Masculin",
        picture: "assets/homme.png",
        nationalite: "Française",
        dateNaissance: new Date(1980, 11, 8),
        lieuNaissance: "Bordeaux",
        telephone: "0123456788",
        adresse: "8 Rue de la Paix",
        ville: "London",
        matiere1: "Histoire",
        matiere2: "Géographie",
        matiere3: "EMC",
        matiere4: "Latin",
        matiere5: "Grec",
        emploiDeTemps: []
    },
    {
        id: 5,
        nom: "Leroux",
        prenom: "Marie",
        adresseEmail: "leroux@gmail.com",
        departement: "Département 3",
        profession: "Enseignante",
        sexe: "Féminin",
        picture: "assets/femme.png",
        nationalite: "Française",
        dateNaissance: new Date(1978, 2, 17),
        lieuNaissance: "Toulouse",
        telephone: "0123456789",
        adresse: "9 Rue des Étoiles",
        ville: "Montreal",
        matiere1: "Arts Plastiques",
        matiere2: "Éducation Musicale",
        matiere3: "Technologie",
        matiere4: "Sciences",
        matiere5: "Physique-Chimie",
        emploiDeTemps: []
    },
    {
        id: 6,
        nom: "Leroy",
        prenom: "Pierre",
        adresseEmail: "leroy@gmail.com",
        departement: "Département 3",
        profession: "Enseignant",
        sexe: "Masculin",
        picture: "assets/homme.png",
        nationalite: "Française",
        dateNaissance: new Date(1977, 1, 18),
        lieuNaissance: "Lille",
        telephone: "0123456790",
        adresse: "20 Boulevard de la Victoire",
        ville: "Montreal",
        matiere1: "Sciences",
        matiere2: "Physique",
        matiere3: "Chimie",
        matiere4: "Biologie",
        matiere5: "Technologie",
        emploiDeTemps: []
    },
    {
        id: 7,
        nom: "Fischer",
        prenom: "Jean",
        adresseEmail: "fisher@gmail.com",
        departement: "Département 1",
        profession: "Professeur",
        sexe: "Masculin",
        picture: "assets/homme.png",
        nationalite: "Française",
        dateNaissance: new Date(1976, 7, 30),
        lieuNaissance: "Strasbourg",
        telephone: "0123456791",
        adresse: "10 Rue de la Victoire",
        ville: "Montreal",
        matiere1: "Sciences",
        matiere2: "Physique-Chimie",
        matiere3: "SVT",
        matiere4: "Technologie",
        matiere5: "Mathématiques",
        emploiDeTemps: []
    },
    {
        id: 8,
        nom: "Ayanna",
        prenom: "Claire",
        adresseEmail: "ayanna@gmail.com",
        departement: "Département 2",
        profession: "Enseignante",
        sexe: "Féminin",
        picture: "assets/femme.png",
        nationalite: "Française",
        dateNaissance: new Date(1979, 3, 18),
        lieuNaissance: "Lyon",
        telephone: "0123456792",
        adresse: "11 Rue de la Paix",
        ville: "Québec",
        matiere1: "Français",
        matiere2: "Littérature",
        matiere3: "Philosophie",
        matiere4: "Anglais",
        matiere5: "Espagnol",
        emploiDeTemps: []
    },
    {
        id: 9,
        nom: "Girard",
        prenom: "Jean",
        adresseEmail: "girard@gmail.com",
        departement: "Département 1",
        profession: "Professeur",
        sexe: "Masculin",
        picture: "assets/homme.png",
        nationalite: "Française",
        dateNaissance: new Date(1976, 7, 30),
        lieuNaissance: "Strasbourg",
        telephone: "0123456791",
        adresse: "12 Rue de la Victoire",
        ville: "Québec",
        matiere1: "Sciences",
        matiere2: "Physique-Chimie",
        matiere3: "SVT",
        matiere4: "Technologie",
        matiere5: "Mathématiques",
        emploiDeTemps: [],
    },
    {
        id: 10,
        nom: "Mayanne",
        prenom: "Claire",
        adresseEmail: "mayanne@gmail.com",
        departement: "Département 2",
        profession: "Enseignante",
        sexe: "Féminin",
        picture: "assets/femme.png",
        nationalite: "Française",
        dateNaissance: new Date(1979, 3, 18),
        lieuNaissance: "Lyon",
        telephone: "0123456792",
        adresse: "13 Rue de la Paix",
        ville: "Québec",
        matiere1: "Français",
        matiere2: "Littérature",
        matiere3: "Philosophie",
        matiere4: "Anglais",
        matiere5: "Espagnol",
        emploiDeTemps: []
    }
];